const Data = [
  {
    id: 1,
    category: "Draft",
    image:
      "https://www.webtrainings.in/wp-content/uploads/2022/05/graphic-designer.jpg",
    name: "XYZ",
    date: "4 / 08 / 22",
    lessons: "1",
    minutes: "13",
    team: "Marketing",
  },
  {
    id: 2,
    category: "Archived",
    image:
      "https://www.shutterstock.com/image-photo/graphic-designer-work-color-swatch-260nw-380124070.jpg",
    name: "Sales vs Marketing",
    date: "4 / 08 / 22",
    lessons: "3",
    minutes: "25",
    team: "Marketing",
  },
  {
    id: 3,
    category: "Live",
    image: "https://www.moople.in/blog/wp-content/uploads/2018/09/31.jpg",
    name: "How to Unclog a Sink",
    date: "4 / 08 / 22",
    lessons: "6",
    minutes: "15",
    team: "Sales",
  },
  {
    id: 4,
    category: "Live",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbBHZG_yiVqYAIoT0IBE32j5Fts00rob1lSQ&usqp=CAU",
    name: "How Google Analytics Ruined Marketing",
    date: "4 / 08 / 22",
    lessons: "3",
    minutes: "25",
    team: "Sales",
  },
  {
    id: 5,
    category: "Live",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxpPs_cWDHKLvC45gy0btz4sNfD9LOArjcdA&usqp=CAU",
    name: "Social Media Marketing 101",
    date: "4 / 08 / 22",
    lessons: "3",
    minutes: "25",
    team: "Marketing",
  },
  {
    id: 6,
    category: "Live",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1QFD4dWge5l_htGkm-gRnBaefKFhxWuJG0w&usqp=CAU",
    name: "Complete training",
    date: "4 / 08 / 22",
    lessons: "2",
    minutes: "15",
    team: "Marketing",
  },
  {
    id: 7,
    category: "Live",
    image: "https://img.freepik.com/free-photo/young-female-designer-working-her-laptop_23-2149142107.jpg",
    name: "Top tricks to Bargaining",
    date: "4 / 08 / 22",
    lessons: "2",
    minutes: "45",
    team: "Marketing",
  },
];
export default Data;
